import { Product, StoreSettings } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-cam-01",
    name: "Smart Home Wireless Pager Doorbell",
    nameAr: "جرس بيجر لاسلكي للمنزل الذكي",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 25.00,
    desc: "Long-range wireless doorbell and caregiver pager system with high quality audio and IP55 waterproof push button.",
    descAr: "نظام جرس بيجر لاسلكي عالي الجودة ومقاوم للماء.",
    imageUrl: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=400"],
    stock: 8,
    visible: true,
    featured: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-02",
    name: "C88B 4.3 Inch HD Screen Mini WIFI Video Doorbell",
    nameAr: "جرس فيديو C88B شاشة 4.3 إنش عالية الوضوح واي فاي",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 133.00,
    desc: "Premium 4.3 inch HD LCD color screen WiFi mini video doorbell with two-way voice and infrared night vision.",
    descAr: "جرس فيديو لاسلكي مزود بشاشة ملونة 4.3 إنش عالية الوضوح ورؤية ليلية.",
    imageUrl: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&q=80&w=400"],
    stock: 10,
    visible: true,
    featured: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-03",
    name: "1080P Video Viewer 2.4G & 5G",
    nameAr: "عرض فيديو 1080P يدعم 2.4G و 5G",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 77.00,
    desc: "Dual band 2.4GHz & 5GHz dual WiFi video viewer with crisp 1080P resolution and smart app notifications.",
    descAr: "نظام رؤية فيديو بدقة 1080P يدعم شبكات الواي فاي المزدوجة 2.4G و 5G.",
    imageUrl: "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?auto=format&fit=crop&q=80&w=400"],
    stock: 5,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-04",
    name: "X6 Smart Video Doorbell Camera",
    nameAr: "كاميرا جرس فيديو ذكية X6",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 69.00,
    desc: "Compact X6 smart video doorbell camera with instant motion detection push notifications and long battery life.",
    descAr: "كاميرا جرس فيديو ذكية X6 مع إشعارات حركة فورية ورؤية ليلية.",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&q=80&w=400"],
    stock: 8,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-05",
    name: "X7 Smart Video Doorbell Camera",
    nameAr: "كاميرا جرس فيديو ذكية X7",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 75.00,
    desc: "Enhanced X7 smart video doorbell camera with wide-angle lens, crystal clear HD audio, and night vision.",
    descAr: "كاميرا جرس فيديو X7 متطورة بعناية فائقة وزاوية رؤية عريضة.",
    imageUrl: "https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&q=80&w=400"],
    stock: 5,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-06",
    name: "4.3-inch Monitor 1080P Video Viewer",
    nameAr: "شاشة عرض فيديو 4.3 إنش بدقة 1080P",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 110.00,
    desc: "Dedicated 4.3-inch indoor monitor with 1080P video streaming, night vision, and easy plug-and-play installation.",
    descAr: "شاشة عرض داخلية 4.3 إنش بدقة 1080P لمراقبة الأبواب بكل وضوح.",
    imageUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=400"],
    stock: 10,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-07",
    name: "Smart Video Doorbell with Remote Voice",
    nameAr: "جرس فيديو ذكي مع تحدث صوتي عن بعد",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 29.00,
    desc: "Affordable smart video doorbell with remote voice changer options and real-time smartphone alerts.",
    descAr: "جرس فيديو ذكي يتيح التواصل الصوتي عن بعد وتغيير الصوت للأمان.",
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=400"],
    stock: 6,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-08",
    name: "Smart Tuya 3MP Mini WiFi PTZ Camera",
    nameAr: "كاميرا تويا ذكية متحركة 3MP صغيرة واي فاي",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 68.00,
    desc: "3 Megapixel ultra-sharp pan-tilt-zoom (PTZ) mini security camera with Tuya app control and motion tracking.",
    descAr: "كاميرا مراقبة صغيرة 3 ميجابكسل متحركة بجميع الاتجاهات مع تتبع الحركة عبر تطبيق تويا.",
    imageUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=400"],
    stock: 1,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-09",
    name: "Home Security Smart Alarm System",
    nameAr: "نظام إنذار وأمان ذكي للمنزل",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 80.00,
    desc: "Comprehensive smart home security alarm kit with door contact sensors, motion detectors, and loud siren.",
    descAr: "نظام أمان وإنذار ذكي شاممل للمنزل مع مستشعرات حركة وصفارة إنذار عالية.",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&q=80&w=400"],
    stock: 5,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-10",
    name: "X10 Smart Video Doorbell Home Security",
    nameAr: "جرس فيديو ذكي للأمان المنزلي X10",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 40.00,
    desc: "High quality X10 video doorbell with HD lens, PIR motion sensing, and cloud backup support.",
    descAr: "جرس فيديو للأمان المنزلي موديل X10 مع استشعار حركة عالي الدقة.",
    imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400"],
    stock: 5,
    visible: true,
    featured: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-11",
    name: "Intelligent Home Wireless Remote Vision",
    nameAr: "نظام رؤية ذكي لاسلكي عن بعد للمنزل",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 25.00,
    desc: "Compact intelligent wireless remote vision camera with easy mobile setup and night vision capabilities.",
    descAr: "نظام رؤية ذكي لاسلكي يوفر بث مباشر عبر الهاتف وسهل التركيب.",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400"],
    stock: 10,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-12",
    name: "Mini Camera WiFi Wireless Security",
    nameAr: "كاميرا صغيرة لاسلكية واي فاي للأمان",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 22.00,
    desc: "Micro size WiFi wireless security camera featuring wide angle view, magnetic mount, and live streaming.",
    descAr: "كاميرا أمان صغيرة جداً لاسلكية تعمل بالواي فاي مع قاعدة مغناطيسية.",
    imageUrl: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=400"],
    stock: 2,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-13",
    name: "U9 Video Doorbell with ERP Motion Detection",
    nameAr: "جرس فيديو U9 مع نظام كشف الحركة ERP",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 39.00,
    desc: "U9 video doorbell with advanced ERP human motion detection algorithm to eliminate false alarms.",
    descAr: "جرس فيديو U9 خفيف مع خوارزمية كشف الحركة الذكية وتنبيهات مستمرة.",
    imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&q=80&w=400"],
    stock: 10,
    visible: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  },
  {
    id: "prod-cam-14",
    name: "Tuya Wireless Home Video Doorbell",
    nameAr: "جرس فيديو لاسلكي للمنزل تويا",
    category: "CAMERA",
    categoryAr: "كاميرات وأجراس",
    basePrice: 75.00,
    desc: "Top-tier Tuya wireless home video doorbell with two-way voice communication, cloud video recording, and rechargeable batteries.",
    descAr: "جرس فيديو لاسلكي للمنزل من تويا مع تحدث ثنائي الاتجاه وتسجيل سحابي.",
    imageUrl: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&q=80&w=400",
    imageUrls: ["https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&q=80&w=400"],
    stock: 6,
    visible: true,
    featured: true,
    options: [],
    variants: [],
    updatedAt: new Date().toISOString()
  }
];

export const DEFAULT_SETTINGS: StoreSettings = {
  title: "ON ALAA STORE",
  phone: "96171135241",
  description: "Premium Mobile Store Lebanon — Your Hub for Power Banks, Grooming Gear, and Authentic Mobile Accessories.",
  instagram: "onlymobilestore.lb",
  locationUrl: "https://maps.google.com/?q=Beirut,Lebanon",
  profilePicUrl: null,
  headerVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-circuit-board-details-close-up-34289-large.mp4",
  titleAr: "متجر علي الإلكتروني",
  descriptionAr: "متجر الهواتف الأول في لبنان - وجهتك للحصول على الشواحن السفرية، ماكينات الحلاقة، وإكسسوارات الهواتف الأصلية."
};
